const ADD_BOOKS = 'ADD_BOOKS';
const SET_FILTER = 'SET_FILTER';
const SET_CATEGORY = 'SET_CATEGORY';
const SET_FILTER_BY_TITLE = 'SET_FILTER_BY_TITLE';
const SET_FILTER_BY_AUTHOR = 'SET_FILTER_BY_AUTHOR';
const SORT = 'SORT';


export default {
    ADD_BOOKS, SET_FILTER, SET_FILTER_BY_TITLE, SET_FILTER_BY_AUTHOR, SET_CATEGORY, SORT
};
